name: shm-modbus # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.3' # just for humans, typically '1.2+git' or '1.3.2'
summary: A collection of applications to simulate a Modbus client  # 79 char long summary
description: |
  Contains command line tools to simulate a Modbus TCP/RTU client.
  The data of the client is stored in shared memory and can be 
  inspected and manipulated with tool contained in this snap

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

build-packages:
  - autoconf
  - automake
  - libtool
  - libreadline-dev

slots:
  shmem-slot:
    interface: shared-memory
    write: ['*'] # paths are relative to /dev/shm
    private: false 
plugs:
  shmem-plug:
    interface: shared-memory
    shared-memory: shmem-slot
    private: false

apps:
  dump-shm:
    command: usr/bin/dump-shm
    plugs: [shmem-plug]
    slots: [shmem-slot] 
  write-shm:
    command: usr/bin/write-shm
    plugs: [shmem-plug]
    slots: [shmem-slot] 
  shared-mem-random:
    command: usr/bin/shared-mem-random
    plugs: [shmem-plug]
    slots: [shmem-slot] 
  stdin-to-modbus-shm:
    command: usr/bin/stdin-to-modbus-shm
    plugs: [shmem-plug]
    slots: [shmem-slot] 
  modbus-tcp-client-shm:
    command: usr/bin/modbus-tcp-client-shm
    plugs: [network, network-bind, shmem-plug]
    slots: [shmem-slot]
  modbus-rtu-client-shm:
    command: usr/bin/modbus-rtu-client-shm
    plugs: [shmem-plug]
    slots: [shmem-slot] 

parts:
  dump-shm:
    source: https://github.com/NikolasK-source/dump_shm.git
    source-type: git
    source-tag: v1.1.0
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCLANG_FORMAT=OFF
      - -DCOMPILER_WARNINGS=OFF
      - -DCMAKE_INSTALL_PREFIX=/usr

  write-shm:
    source: https://github.com/NikolasK-source/write_shm.git
    source-type: git
    source-tag: v0.1.3
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCLANG_FORMAT=OFF
      - -DCOMPILER_WARNINGS=OFF
      - -DCMAKE_INSTALL_PREFIX=/usr
  
  shared-mem-random:
    source: https://github.com/NikolasK-source/shared_mem_random.git
    source-type: git
    source-tag: v1.1.0
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCLANG_FORMAT=OFF
      - -DCOMPILER_WARNINGS=OFF
      - -DCMAKE_INSTALL_PREFIX=/usr

  stdin-to-modbus-shm:
    source: https://github.com/NikolasK-source/stdin_to_modbus_shm.git
    source-type: git
    source-tag: v1.1.1
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCLANG_FORMAT=OFF
      - -DCOMPILER_WARNINGS=OFF
      - -DCMAKE_INSTALL_PREFIX=/usr
  
  modbus-tcp-client-shm:
    source: https://github.com/NikolasK-source/modbus_tcp_client_shm.git
    source-type: git
    source-tag: v1.3.1
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCLANG_FORMAT=OFF
      - -DCOMPILER_WARNINGS=OFF
      - -DCMAKE_INSTALL_PREFIX=/usr

  modbus-rtu-client-shm:
    source: https://github.com/NikolasK-source/modbus_rtu_client_shm.git
    source-type: git
    source-tag: v0.2.4
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCLANG_FORMAT=OFF
      - -DCOMPILER_WARNINGS=OFF
      - -DCMAKE_INSTALL_PREFIX=/usr
