name: shm-modbus # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '2.1.2-3' # just for humans, typically '1.2+git' or '1.3.2'
adopt-info: shm-modbus
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

build-packages:
  - autoconf
  - automake
  - libtool
  - libreadline-dev
  - libmodbus-dev

plugs:
  shm:
    interface: system-files
    write:
      - /dev/shm

apps:
  shm-modbus:
    command: usr/bin/shm-modbus
    plugs:
      - network
      - network-bind
      - serial-port
      - shm
      - desktop
      - wayland
      - x11
  dump-shm:
    command: usr/bin/dump-shm
    plugs: [shm]
    aliases: [dump-shm]
  write-shm:
    command: usr/bin/write-shm
    plugs: [shm]
    aliases: [write-shm]
  shared-mem-random:
    command: usr/bin/shared-mem-random
    plugs: [shm]
    aliases: [shared-mem-random]
  stdin-to-modbus-shm:
    command: usr/bin/stdin-to-modbus-shm
    plugs: [shm]
    aliases: [stdin-to-modbus-shm]
  modbus-tcp-client-shm:
    command: usr/bin/modbus-tcp-client-shm
    plugs: [network, network-bind, shm]
    aliases: [modbus-tcp-client-shm]
  modbus-rtu-client-shm:
    command: usr/bin/modbus-rtu-client-shm
    plugs: [serial-port, shm]
    aliases: [modbus-rtu-client-shm]
  signal-gen:
    command: usr/bin/signal-gen
  shm-modbus-signal-gen:
    command: usr/bin/signal-gen
    aliases: [shm-modbus-signal-gen]
  wago-modbus-coupler-shm:
    command: usr/bin/wago-modbus-coupler-shm
    plugs: [shm]
    aliases: [wago-modbus-coupler-shm]
  shm-format:
    command: usr/bin/shm-format
    plugs: [shm]
    aliases: [shm-format]
  gui:
    command: bin/shm-modbus-gui
    plugs: 
      - network
      - network-bind
      - serial-port
      - shm
      - desktop
      - wayland
      - x11
    environment:
      QT_PLUGIN_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins"
  shm-modbus-gui:
    command: bin/shm-modbus-gui
    plugs: 
      - network
      - network-bind
      - serial-port
      - shm
      - desktop
      - wayland
      - x11
    environment:
      QT_PLUGIN_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins"
    aliases: [shm-modbus-gui]

parts:
  cxxshm:
    source: https://github.com/NikolasK-source/cxxshm.git
    source-type: git
    source-tag: v2.0.2
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCLANG_FORMAT=OFF
      - -DCOMPILER_WARNINGS=OFF
      - -DCLANG_TIDY=OFF
      - -DBUILD_DOC=OFF
      - -DENABLE_TEST=OFF
      - -DCMAKE_INSTALL_PREFIX=/usr
    stage:
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libcxxshm.so
      - usr/include/cxxshm.hpp
      - usr/include/cxxshm_version_info.hpp
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxshm/cxxshmTargets.cmake
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxshm/cxxshmTargets-release.cmake
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxshm/cxxshmConfig.cmake
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxshm/cxxshmConfigVersion.cmake

  cxxopts:
    source: https://github.com/jarro2783/cxxopts.git
    source-type: git
    source-tag: v3.2.0
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCXXOPTS_BUILD_EXAMPLES=OFF
      - -DCXXOPTS_BUILD_TESTS=OFF
      - -DCMAKE_INSTALL_PREFIX=/usr
    stage:
      - usr/lib/cmake/cxxopts/cxxopts-config.cmake
      - usr/lib/cmake/cxxopts/cxxopts-config-version.cmake
      - usr/lib/cmake/cxxopts/cxxopts-targets.cmake
      - usr/include/cxxopts.hpp
      - usr/lib/pkgconfig/cxxopts.pc

  cxxsemaphore:
    source: https://github.com/NikolasK-source/cxxsemaphore.git
    source-type: git
    source-tag: v2.0.2
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCLANG_FORMAT=OFF
      - -DCOMPILER_WARNINGS=OFF
      - -DCLANG_TIDY=OFF
      - -DBUILD_DOC=OFF
      - -DENABLE_TEST=OFF
      - -DCMAKE_INSTALL_PREFIX=/usr
    stage:
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libcxxsemaphore.so
      - usr/include/cxxsemaphore.hpp
      - usr/include/cxxsemaphore_version_info.hpp
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxsemaphore/cxxsemaphoreTargets.cmake
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxsemaphore/cxxsemaphoreTargets-release.cmake
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxsemaphore/cxxsemaphoreConfig.cmake
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxsemaphore/cxxsemaphoreConfigVersion.cmake

  cxxitimer:
    source: https://github.com/NikolasK-source/cxxitimer.git
    source-type: git
    source-tag: v2.0.2
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCLANG_FORMAT=OFF
      - -DCOMPILER_WARNINGS=OFF
      - -DCLANG_TIDY=OFF
      - -DBUILD_DOC=OFF
      - -DENABLE_TEST=OFF
      - -DCMAKE_INSTALL_PREFIX=/usr
    stage:
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libcxxitimer.so
      - usr/include/cxxitimer.hpp
      - usr/include/cxxitimer_version_info.hpp
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxitimer/cxxitimerTargets.cmake
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxitimer/cxxitimerTargets-release.cmake
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxitimer/cxxitimerConfig.cmake
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxitimer/cxxitimerConfigVersion.cmake

  nlohmann_json:
    source: https://github.com/nlohmann/json.git
    source-type: git
    source-tag: v3.11.3
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DJSON_BuildTests=OFF
    stage:
      - usr/include/nlohmann
      - usr/share/cmake/nlohmann_json
      - usr/share/pkgconfig/nlohmann_json.pc

  dump-shm:
    source: https://github.com/SHMModbus/dump_shm.git
    source-type: git
    source-tag: v1.3.1
    after:
      - cxxshm
      - cxxsemaphore
      - nlohmann_json
      - cxxopts
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCLANG_FORMAT=OFF
      - -DCOMPILER_WARNINGS=OFF
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DENABLE_TEST=OFF
      - -Dcxxshm_DIR=${SNAPCRAFT_STAGE}/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxshm/
      - -Dcxxitimer_DIR=${SNAPCRAFT_STAGE}/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxitimer/
      - -Dcxxsemaphore_DIR=${SNAPCRAFT_STAGE}/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxsemaphore/
      - -Dcxxopts_DIR=${SNAPCRAFT_STAGE}/usr/lib/cmake/cxxopts/
      - -Dnlohmann_json_DIR=${SNAPCRAFT_STAGE}/usr/share/cmake/nlohmann_json/
    build-attributes:
      - enable-patchelf
    stage:
      - usr/bin/dump-shm

  write-shm:
    source: https://github.com/SHMModbus/write_shm.git
    source-type: git
    source-tag: v1.1.1
    after:
      - cxxshm
      - cxxsemaphore
      - nlohmann_json
      - cxxopts
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCLANG_FORMAT=OFF
      - -DCOMPILER_WARNINGS=OFF
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DENABLE_TEST=OFF
      - -Dcxxshm_DIR=${SNAPCRAFT_STAGE}/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxshm/
      - -Dcxxitimer_DIR=${SNAPCRAFT_STAGE}/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxitimer/
      - -Dcxxsemaphore_DIR=${SNAPCRAFT_STAGE}/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxsemaphore/
      - -Dcxxopts_DIR=${SNAPCRAFT_STAGE}/usr/lib/cmake/cxxopts/
      - -Dnlohmann_json_DIR=${SNAPCRAFT_STAGE}/usr/share/cmake/nlohmann_json/
    build-attributes:
      - enable-patchelf
    stage:
      - usr/bin/write-shm
  
  shared-mem-random:
    source: https://github.com/SHMModbus/shared_mem_random.git
    source-type: git
    source-tag: v1.4.1
    after:
      - cxxshm
      - cxxsemaphore
      - cxxitimer
      - nlohmann_json
      - cxxopts
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCLANG_FORMAT=OFF
      - -DCOMPILER_WARNINGS=OFF
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DENABLE_TEST=OFF
      - -Dcxxshm_DIR=${SNAPCRAFT_STAGE}/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxshm/
      - -Dcxxitimer_DIR=${SNAPCRAFT_STAGE}/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxitimer/
      - -Dcxxsemaphore_DIR=${SNAPCRAFT_STAGE}/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxsemaphore/
      - -Dcxxopts_DIR=${SNAPCRAFT_STAGE}/usr/lib/cmake/cxxopts/
      - -Dnlohmann_json_DIR=${SNAPCRAFT_STAGE}/usr/share/cmake/nlohmann_json/
    build-attributes:
      - enable-patchelf
    stage:
      - usr/bin/shared-mem-random

  shm-format:
    source: https://github.com/SHMModbus/shm_format
    source-type: git
    source-tag: v2.0.1
    after:
      - cxxshm
      - cxxsemaphore
      - cxxitimer
      - nlohmann_json
      - cxxopts
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCLANG_FORMAT=OFF
      - -DCOMPILER_WARNINGS=OFF
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DENABLE_TEST=OFF
      - -Dcxxshm_DIR=${SNAPCRAFT_STAGE}/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxshm/
      - -Dcxxitimer_DIR=${SNAPCRAFT_STAGE}/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxitimer/
      - -Dcxxsemaphore_DIR=${SNAPCRAFT_STAGE}/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxsemaphore/
      - -Dcxxopts_DIR=${SNAPCRAFT_STAGE}/usr/lib/cmake/cxxopts/
      - -Dnlohmann_json_DIR=${SNAPCRAFT_STAGE}/usr/share/cmake/nlohmann_json/
    build-attributes:
      - enable-patchelf
    stage:
      - usr/bin/shm-format

  stdin-to-modbus-shm:
    source: https://github.com/SHMModbus/stdin_to_modbus_shm.git
    source-type: git
    source-tag: v1.5.0
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCLANG_FORMAT=OFF
      - -DCOMPILER_WARNINGS=OFF
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DENABLE_TEST=OFF
      - -Dcxxshm_DIR=${SNAPCRAFT_STAGE}/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxshm/
      - -Dcxxitimer_DIR=${SNAPCRAFT_STAGE}/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxitimer/
      - -Dcxxsemaphore_DIR=${SNAPCRAFT_STAGE}/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxsemaphore/
      - -Dcxxopts_DIR=${SNAPCRAFT_STAGE}/usr/lib/cmake/cxxopts/
      - -Dnlohmann_json_DIR=${SNAPCRAFT_STAGE}/usr/share/cmake/nlohmann_json/
    build-attributes:
      - enable-patchelf
    stage:
      - usr/bin/stdin-to-modbus-shm
  
  modbus-tcp-client-shm:
    source: https://github.com/SHMModbus/modbus_tcp_client_shm.git
    source-type: git
    source-tag: v1.6.3
    after:
      - cxxshm
      - cxxsemaphore
      - nlohmann_json
      - cxxopts
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCLANG_FORMAT=OFF
      - -DCOMPILER_WARNINGS=OFF
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DENABLE_TEST=OFF
      - -Dcxxshm_DIR=${SNAPCRAFT_STAGE}/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxshm/
      - -Dcxxitimer_DIR=${SNAPCRAFT_STAGE}/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxitimer/
      - -Dcxxsemaphore_DIR=${SNAPCRAFT_STAGE}/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxsemaphore/
      - -Dcxxopts_DIR=${SNAPCRAFT_STAGE}/usr/lib/cmake/cxxopts/
      - -Dnlohmann_json_DIR=${SNAPCRAFT_STAGE}/usr/share/cmake/nlohmann_json/
    build-attributes:
      - enable-patchelf
    stage:
      - usr/bin/modbus-tcp-client-shm
    stage-packages:
      - libmodbus-dev

  modbus-rtu-client-shm:
    source: https://github.com/SHMModbus/modbus_rtu_client_shm.git
    source-type: git
    source-tag: v0.4.1
    after:
      - cxxshm
      - cxxsemaphore
      - nlohmann_json
      - cxxopts
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCLANG_FORMAT=OFF
      - -DCOMPILER_WARNINGS=OFF
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DENABLE_TEST=OFF
      - -Dcxxshm_DIR=${SNAPCRAFT_STAGE}/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxshm/
      - -Dcxxitimer_DIR=${SNAPCRAFT_STAGE}/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxitimer/
      - -Dcxxsemaphore_DIR=${SNAPCRAFT_STAGE}/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxsemaphore/
      - -Dcxxopts_DIR=${SNAPCRAFT_STAGE}/usr/lib/cmake/cxxopts/
      - -Dnlohmann_json_DIR=${SNAPCRAFT_STAGE}/usr/share/cmake/nlohmann_json/
    build-attributes:
      - enable-patchelf
    stage:
      - usr/bin/modbus-rtu-client-shm
    stage-packages:
      - libmodbus-dev

  signal-gen:
    source: https://github.com/SHMModbus/shm-modbus-signal-gen.git
    source-type: git
    source-tag: v1.0.2
    after:
      - cxxshm
      - cxxsemaphore
      - nlohmann_json
      - cxxopts
      - gui
    plugin: python
    build-attributes:
      - enable-patchelf
    override-build: |
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/share/signal-gen
      install -Dm555 src/*.py ${SNAPCRAFT_PART_INSTALL}/usr/share/signal-gen
      chmod +x ${SNAPCRAFT_PART_INSTALL}/usr/share/signal-gen/signalgen.py
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/bin
      ln -s ../share/signal-gen/signalgen.py ${SNAPCRAFT_PART_INSTALL}/usr/bin/signal-gen
      ln -s ../share/signal-gen/signalgen.py ${SNAPCRAFT_PART_INSTALL}/usr/bin/shm-modbus-signal-gen
    stage:
      - usr/share/signal-gen
      - usr/bin/signal-gen
      - usr/bin/shm-modbus-signal-gen

  gui:
    source: https://github.com/SHMModbus/shm_modbus_gui.git
    source-type: git
    source-tag: v2.1.1-flatpak
    after:
      - cxxshm
      - cxxsemaphore
      - nlohmann_json
      - cxxopts
    plugin: python
    python-packages:
     - pyside6==6.2.4
    stage-packages:
      - libgl1
      - libxkbcommon0
      - libegl1
      - libfontconfig1
      - libpulse0
      - libxcb-cursor0
      - qt6-base-dev
      - bsdextrautils
      - libmodbus-dev

    
  wago-modbus-coupler-shm:
    source: https://github.com/SHMModbus/wago_modbus_coupler_shm.git
    source-type: git
    source-tag: v1.1.1
    after:
      - cxxshm
      - cxxsemaphore
      - nlohmann_json
      - cxxopts
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCLANG_FORMAT=OFF
      - -DCOMPILER_WARNINGS=OFF
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DENABLE_TEST=OFF
      - -Dcxxshm_DIR=${SNAPCRAFT_STAGE}/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxshm/
      - -Dcxxitimer_DIR=${SNAPCRAFT_STAGE}/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxitimer/
      - -Dcxxsemaphore_DIR=${SNAPCRAFT_STAGE}/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/cxxsemaphore/
      - -Dcxxopts_DIR=${SNAPCRAFT_STAGE}/usr/lib/cmake/cxxopts/
      - -Dnlohmann_json_DIR=${SNAPCRAFT_STAGE}/usr/share/cmake/nlohmann_json/
    build-attributes:
      - enable-patchelf
    override-build: |
      snapcraftctl build
      mv ${SNAPCRAFT_PART_INSTALL}/usr/bin/wago_modbus_coupler_shm ${SNAPCRAFT_PART_INSTALL}/usr/bin/wago-modbus-coupler-shm
    stage:
      - usr/bin/wago-modbus-coupler-shm
      
  shm-modbus:
    source: .
    source-type: local
    plugin: nil
    override-build: |
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/share/shm-modbus
      install -m555 shm-modbus ${SNAPCRAFT_PART_INSTALL}/usr/share/shm-modbus/shm-modbus.sh
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/bin
      ln -s ../share/shm-modbus/shm-modbus.sh ${SNAPCRAFT_PART_INSTALL}/usr/bin/shm-modbus
    parse-info:
      - io.github.shmmodbus.shm-modbus.metainfo.xml
