name: shm-modbus # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.3.0-1' # just for humans, typically '1.2+git' or '1.3.2'
summary: A collection of applications to simulate a Modbus client  # 79 char long summary
description: |
  Contains command line tools to simulate a Modbus TCP/RTU client.
  The data of the client is stored in shared memory and can be 
  inspected and manipulated with tool contained in this snap

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

build-packages:
  - autoconf
  - automake
  - libtool
  - libreadline-dev

apps:
  dump-shm:
    command: usr/bin/dump-shm
  write-shm:
    command: usr/bin/write-shm
  shared-mem-random:
    command: usr/bin/shared-mem-random
  stdin-to-modbus-shm:
    command: usr/bin/stdin-to-modbus-shm
  modbus-tcp-client-shm:
    command: usr/bin/modbus-tcp-client-shm
  modbus-rtu-client-shm:
    command: usr/bin/modbus-rtu-client-shm
  signal-gen:
    command: bin/signalgen
  wago-modbus-coupler-shm:
    command: usr/bin/wago_modbus_coupler_shm

parts:
  dump-shm:
    source: https://github.com/NikolasK-source/dump_shm.git
    source-type: git
    source-tag: v1.1.0
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCLANG_FORMAT=OFF
      - -DCOMPILER_WARNINGS=OFF
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-attributes:
      - enable-patchelf

  write-shm:
    source: https://github.com/NikolasK-source/write_shm.git
    source-type: git
    source-tag: v0.1.3
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCLANG_FORMAT=OFF
      - -DCOMPILER_WARNINGS=OFF
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-attributes:
      - enable-patchelf
  
  shared-mem-random:
    source: https://github.com/NikolasK-source/shared_mem_random.git
    source-type: git
    source-tag: v1.1.0
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCLANG_FORMAT=OFF
      - -DCOMPILER_WARNINGS=OFF
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-attributes:
      - enable-patchelf

  stdin-to-modbus-shm:
    source: https://github.com/NikolasK-source/stdin_to_modbus_shm.git
    source-type: git
    source-tag: v1.2.0
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCLANG_FORMAT=OFF
      - -DCOMPILER_WARNINGS=OFF
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-attributes:
      - enable-patchelf
  
  modbus-tcp-client-shm:
    source: https://github.com/NikolasK-source/modbus_tcp_client_shm.git
    source-type: git
    source-tag: v1.5.0
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCLANG_FORMAT=OFF
      - -DCOMPILER_WARNINGS=OFF
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-attributes:
      - enable-patchelf

  modbus-rtu-client-shm:
    source: https://github.com/NikolasK-source/modbus_rtu_client_shm.git
    source-type: git
    source-tag: v0.2.5
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCLANG_FORMAT=OFF
      - -DCOMPILER_WARNINGS=OFF
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-attributes:
      - enable-patchelf

  signal-gen:
    source: https://github.com/NikolasK-source/shm-modbus-signal-gen.git
    source-type: git
    source-tag: v1.0.2
    plugin: python
    stage-packages: [python3-minimal, python3.10-minimal]
    build-attributes:
      - enable-patchelf
    
  wago-modbus-coupler-shm:
    source: https://github.com/NikolasK-source/wago_modbus_coupler_shm.git
    source-type: git
    source-tag: v1.1.1
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCLANG_FORMAT=OFF
      - -DCOMPILER_WARNINGS=OFF
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-attributes:
      - enable-patchelf
      